#!/bin/bash

number=$RANDOM
range=3
let number=( $number % $range )
#echo $number
dir=$HOME/.fluxbox/backgrounds/
name=official
wallpaper=$dir$name$number.png

cp $wallpaper $dir/accual_background.png
